import { FAQAccordion } from '../../components/marketing/Primitives';
import { PublicLayout as PublicShell } from '../../components/marketing/PublicLayout';
import { RiskNotice } from '../../components/marketing/Primitives';
import { Metadata } from '../public/Metadata';
import { type FormEvent } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { insightService, type Article } from './insightService';

function Loading() { return <p aria-busy="true" className="py-12">Loading editorial content...</p>; }
function ErrorState() { return <p role="alert" className="my-8 rounded-lg border border-rose-300 bg-rose-50 p-4">Editorial content is unavailable. Please try again.</p>; }
export function ArticleCard({ item }: { item: Article }) { return <article className="flex flex-col rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-4 flex flex-wrap justify-between gap-3 text-xs font-semibold uppercase text-slate-500"><span>{item.category_name}</span>{item.published_at && <span>{new Date(item.published_at).toLocaleDateString()}</span>}</div><h2 className="text-xl font-semibold"><Link to={`/insights/${item.slug}`}>{item.title}</Link></h2><p className="mt-3 flex-1 text-slate-600">{item.excerpt}</p><div className="mt-5 flex flex-wrap gap-2">{item.tags.map((tag) => <span className="rounded bg-slate-100 px-2 py-1 text-xs text-slate-600" key={tag.id}>{tag.name}</span>)}</div><Link className="mt-6 font-semibold text-blue-800" to={`/insights/${item.slug}`}>Read insight</Link></article>; }
export function InsightsPage() {
  const [params, setParams] = useSearchParams(); const filters = { category: params.get('category') ?? '', tag: params.get('tag') ?? '', search: params.get('search') ?? '', page: Number(params.get('page') ?? 1), per_page: 9, sort: '-published_at' };
  const insights = useQuery({ queryKey: ['insights', filters], queryFn: ({ signal }) => insightService.publicList(filters, signal) }); const featured = useQuery({ queryKey: ['insights', 'featured'], queryFn: ({ signal }) => insightService.publicList({ featured: '1', per_page: 1, sort: '-published_at' }, signal) }); const categories = useQuery({ queryKey: ['insight-categories'], queryFn: ({ signal }) => insightService.categories(signal) }); const tags = useQuery({ queryKey: ['tags'], queryFn: ({ signal }) => insightService.tags(signal) });
  function filter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const next = new URLSearchParams(); for (const key of ['search', 'category', 'tag']) { const value = String(data.get(key) ?? ''); if (value) next.set(key, value); } setParams(next); }
  const lead = featured.data?.data[0];
  return <PublicShell><Metadata title="Insights" /><main tabIndex={-1} id="content" className="mx-auto max-w-6xl px-5 py-14"><p className="font-semibold uppercase tracking-widest text-blue-800">Editorial publishing</p><h1 className="mt-2 text-4xl font-semibold">Insights</h1><p className="mt-4 max-w-3xl text-lg text-slate-600">Read research notes, educational commentary, and company perspectives on digital asset wealth management.</p>{lead && <section className="mt-10 rounded-lg bg-[#07192f] p-8 text-white"><p className="text-sm font-semibold uppercase text-emerald-200">Featured insight</p><h2 className="mt-2 text-3xl font-semibold"><Link to={`/insights/${lead.slug}`}>{lead.title}</Link></h2><p className="mt-3 max-w-3xl text-slate-300">{lead.excerpt}</p></section>}<form className="my-8 grid gap-4 rounded-lg bg-white p-5 shadow-sm md:grid-cols-4" onSubmit={filter}><label>Search<input name="search" defaultValue={filters.search} className="mt-1 w-full rounded border p-2" /></label><label>Category<select name="category" defaultValue={filters.category} className="mt-1 w-full rounded border p-2"><option value="">All categories</option>{categories.data?.data.map((category) => <option value={category.slug} key={category.id}>{category.name}</option>)}</select></label><label>Tag<select name="tag" defaultValue={filters.tag} className="mt-1 w-full rounded border p-2"><option value="">All tags</option>{tags.data?.data.map((tag) => <option value={tag.slug} key={tag.id}>{tag.name}</option>)}</select></label><button className="self-end rounded bg-[#0b376d] px-4 py-2 font-semibold text-white">Apply filters</button></form>{insights.isPending ? <Loading /> : insights.isError ? <ErrorState /> : insights.data.data.length === 0 ? <p className="py-12">No published insights match these filters.</p> : <div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{insights.data.data.map((item) => <ArticleCard item={item} key={item.uuid} />)}</div>}{(insights.data?.meta.total_pages ?? 0) > 1 && <nav aria-label="Insights pagination" className="mt-8 flex gap-3"><button disabled={filters.page <= 1} onClick={() => { params.set('page', String(filters.page - 1)); setParams(params); }}>Previous</button><span>Page {filters.page} of {insights.data?.meta.total_pages}</span><button disabled={filters.page >= (insights.data?.meta.total_pages ?? 1)} onClick={() => { params.set('page', String(filters.page + 1)); setParams(params); }}>Next</button></nav>}</main></PublicShell>;
}
export function InsightDetailPage() {
  const { slug = '' } = useParams(); const query = useQuery({ queryKey: ['insight', slug], queryFn: ({ signal }) => insightService.publicDetail(slug, signal), enabled: Boolean(slug) }); const item = query.data?.data;
  return <PublicShell><Metadata title={item?.title ?? "Insight"} seo={item?.seo} unavailable={!item} /><main tabIndex={-1} id="content" className="mx-auto max-w-4xl px-5 py-14">{query.isPending ? <Loading /> : query.isError || !item ? <ErrorState /> : <><nav aria-label="Breadcrumb" className="text-sm text-slate-600"><Link to="/insights">Insights</Link> / {item.title}</nav><p className="mt-10 font-semibold uppercase tracking-wide text-blue-800">{item.category_name}</p><h1 className="mt-2 text-4xl font-semibold">{item.title}</h1><p className="mt-4 text-slate-600">By {item.author}{item.published_at ? ` on ${new Date(item.published_at).toLocaleDateString()}` : ''}</p><p className="mt-5 text-xl text-slate-600">{item.excerpt}</p><section className="prose mt-10 max-w-none" dangerouslySetInnerHTML={{ __html: item.content }} /><RiskNotice />{(item.related?.length ?? 0) > 0 && <section className="mt-12"><h2 className="text-2xl font-semibold">Related insights</h2><div className="mt-5 grid gap-5 md:grid-cols-3">{item.related?.map((related) => <ArticleCard item={related} key={related.uuid} />)}</div></section>}</>}</main></PublicShell>;
}
export function FAQPage() {
  const query = useQuery({ queryKey: ['faq'], queryFn: ({ signal }) => insightService.faq(undefined, signal) });
  return <PublicShell><Metadata title="Frequently asked questions" /><main tabIndex={-1} id="content" className="mx-auto max-w-4xl px-5 py-14"><h1 className="text-4xl font-semibold">Frequently asked questions</h1><p className="mt-4 text-lg text-slate-600">General answers about PerrymanFinance services, process, and risk information.</p>{query.isPending ? <Loading /> : query.isError ? <ErrorState /> : query.data.data.length === 0 ? <p className="py-12">No published FAQs are available.</p> : <section className="mt-8 rounded-lg bg-white p-6 shadow-sm">{query.data.data.map((item) => <FAQAccordion question={item.question} answer={item.answer} key={item.id} />)}</section>}</main></PublicShell>;
}
