import { FAQAccordion } from '../../components/marketing/Primitives';
import { PublicLayout as PublicShell } from '../../components/marketing/PublicLayout';
import { RiskNotice } from '../../components/marketing/Primitives';
import { Metadata } from '../public/Metadata';
import { type FormEvent } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { insightService, type Article } from './insightService';

function Loading() { return <p aria-busy="true" className="py-12">Loading editorial content...</p>; }
function ErrorState() { return <p role="alert" className="my-8 rounded-lg border border-rose-300 bg-rose-50 p-4">Editorial content is unavailable. Please try again.</p>; }
export function ArticleCard({ item }: { item: Article }) { return <article className="flex flex-col rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-4 flex flex-wrap justify-between gap-3 text-xs font-semibold uppercase text-slate-500"><span>{item.category_name}</span>{item.published_at && <span>{new Date(item.published_at).toLocaleDateString()}</span>}</div><h2 className="text-xl font-semibold"><Link to={`/insights/${item.slug}`}>{item.title}</Link></h2><p className="mt-3 flex-1 text-slate-600">{item.excerpt}</p><div className="mt-5 flex flex-wrap gap-2">{item.tags.map((tag) => <span className="rounded bg-slate-100 px-2 py-1 text-xs text-slate-600" key={tag.id}>{tag.name}</span>)}</div><Link className="mt-6 font-semibold text-blue-800" to={`/insights/${item.slug}`}>Read insight</Link></article>; }
export function InsightsPage() {
  const [params, setParams] = useSearchParams(); const filters = { category: params.get('category') ?? '', tag: params.get('tag') ?? '', search: params.get('search') ?? '', page: Number(params.get('page') ?? 1), per_page: 9, sort: '-published_at' };
  const insights = useQuery({ queryKey: ['insights', filters], queryFn: ({ signal }) => insightService.publicList(filters, signal) }); const featured = useQuery({ queryKey: ['insights', 'featured'], queryFn: ({ signal }) => insightService.publicList({ featured: '1', per_page: 1, sort: '-published_at' }, signal) }); const categories = useQuery({ queryKey: ['insight-categories'], queryFn: ({ signal }) => insightService.categories(signal) }); const tags = useQuery({ queryKey: ['tags'], queryFn: ({ signal }) => insightService.tags(signal) });
  function filter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const next = new URLSearchParams(); for (const key of ['search', 'category', 'tag']) { const value = String(data.get(key) ?? ''); if (value) next.set(key, value); } setParams(next); }
  const lead = featured.data?.data[0];
  return <PublicShell><Metadata title="Insights" /><main tabIndex={-1} id="content" className="mx-auto max-w-6xl px-5 py-14"><p className="font-semibold uppercase tracking-widest text-blue-800">Editorial publishing</p><h1 className="mt-2 text-4xl font-semibold">Insights</h1><p className="mt-4 max-w-3xl text-lg text-slate-600">Read research notes, educational commentary, and company perspectives on digital asset wealth management.</p>{lead && <section className="mt-10 rounded-lg bg-[#07192f] p-8 text-white"><p className="text-sm font-semibold uppercase text-emerald-200">Featured insight</p><h2 className="mt-2 text-3xl font-semibold"><Link to={`/insights/${lead.slug}`}>{lead.title}</Link></h2><p className="mt-3 max-w-3xl text-slate-300">{lead.excerpt}</p></section>}<form className="my-8 grid gap-4 rounded-lg bg-white p-5 shadow-sm md:grid-cols-4" onSubmit={filter}><label>Search<input name="search" defaultValue={filters.search} className="mt-1 w-full rounded border p-2" /></label><label>Category<select name="category" defaultValue={filters.category} className="mt-1 w-full rounded border p-2"><option value="">All categories</option>{categories.data?.data.map((category) => <option value={category.slug} key={category.id}>{category.name}</option>)}</select></label><label>Tag<select name="tag" defaultValue={filters.tag} className="mt-1 w-full rounded border p-2"><option value="">All tags</option>{tags.data?.data.map((tag) => <option value={tag.slug} key={tag.id}>{tag.name}</option>)}</select></label><button className="self-end rounded bg-[#0b376d] px-4 py-2 font-semibold text-white">Apply filters</button></form>{insights.isPending ? <Loading /> : insights.isError ? <ErrorState /> : insights.data.data.length === 0 ? <p className="py-12">No published insights match these filters.</p> : <div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{insights.data.data.map((item) => <ArticleCard item={item} key={item.uuid} />)}</div>}{(insights.data?.meta.total_pages ?? 0) > 1 && <nav aria-label="Insights pagination" className="mt-8 flex gap-3"><button disabled={filters.page <= 1} onClick={() => { params.set('page', String(filters.page - 1)); setParams(params); }}>Previous</button><span>Page {filters.page} of {insights.data?.meta.total_pages}</span><button disabled={filters.page >= (insights.data?.meta.total_pages ?? 1)} onClick={() => { params.set('page', String(filters.page + 1)); setParams(params); }}>Next</button></nav>}</main></PublicShell>;
}
export function InsightDetailPage() {
  const { slug = '' } = useParams(); const query = useQuery({ queryKey: ['insight', slug], queryFn: ({ signal }) => insightService.publicDetail(slug, signal), enabled: Boolean(slug) }); const item = query.data?.data;
  const canonical = item?.seo?.canonical_url || (import.meta.env.VITE_SITE_URL ? `${String(import.meta.env.VITE_SITE_URL).replace(/\/$/, '')}/insights/${item?.slug ?? slug}` : undefined);
  const articleSchema = item ? { '@context': 'https://schema.org', '@type': 'Article', headline: item.title, description: item.excerpt, author: { '@type': 'Person', name: item.author }, datePublished: item.published_at ?? undefined, mainEntityOfPage: canonical } : undefined;
  return <PublicShell><Metadata title={item?.title ?? "Insight"} seo={item?.seo} unavailable={!item} jsonLd={articleSchema} ogType="article" /><main tabIndex={-1} id="content" className="mx-auto max-w-4xl px-5 py-14">{query.isPending ? <Loading /> : query.isError || !item ? <ErrorState /> : <><nav aria-label="Breadcrumb" className="text-sm text-slate-600"><Link to="/insights">Insights</Link> / {item.title}</nav><p className="mt-10 font-semibold uppercase tracking-wide text-blue-800">{item.category_name}</p><h1 className="mt-2 text-4xl font-semibold">{item.title}</h1><p className="mt-4 text-slate-600">By {item.author}{item.published_at ? ` on ${new Date(item.published_at).toLocaleDateString()}` : ''}</p><p className="mt-5 text-xl text-slate-600">{item.excerpt}</p><section className="prose mt-10 max-w-none" dangerouslySetInnerHTML={{ __html: item.content }} /><RiskNotice />{(item.related?.length ?? 0) > 0 && <section className="mt-12"><h2 className="text-2xl font-semibold">Related insights</h2><div className="mt-5 grid gap-5 md:grid-cols-3">{item.related?.map((related) => <ArticleCard item={related} key={related.uuid} />)}</div></section>}</>}</main></PublicShell>;
}
export function FAQPage() {
  const query = useQuery({ queryKey: ['faq'], queryFn: ({ signal }) => insightService.faq(undefined, signal) });
  const faqs = query.data?.data ?? [];
  const categoryLabels: Record<string, string> = { general: 'General', services: 'Services', 'getting-started': 'Getting Started', 'investment-opportunities': 'Investment Opportunities', 'platform-boundaries': 'Platform Boundaries', 'privacy-and-security': 'Privacy and Security', 'customer-support': 'Customer Support' };
  const groups = faqs.reduce<Record<string, typeof faqs>>((all, item) => { const category = item.category?.trim() || 'general'; (all[category] ??= []).push(item); return all; }, {});
  const faqSchema = faqs.length ? { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer.replace(/<[^>]+>/g, '') } })) } : undefined;
  return <PublicShell><Metadata title="Frequently Asked Questions" jsonLd={faqSchema} /><main tabIndex={-1} id="content" className="section-wrap"><div className="max-w-4xl"><p className="eyebrow">Client information</p><h1 className="mt-4 text-4xl font-semibold text-white sm:text-5xl">Frequently asked questions</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-slate-300">Find clear answers about PerrymanFinance services, published opportunities, risk information, and how to reach the right team.</p></div>{query.isPending ? <Loading /> : query.isError ? <section className="mt-10" aria-labelledby="faq-unavailable"><h2 id="faq-unavailable" className="sr-only">Frequently asked questions unavailable</h2><div role="alert" className="rounded-lg border border-rose-300/30 bg-rose-950/20 p-6 text-slate-100"><p className="font-semibold">Frequently asked questions are temporarily unavailable.</p><p className="mt-2 text-slate-300">Please try again or contact client services.</p><button className="button mt-4" onClick={() => void query.refetch()}>Try again</button></div></section> : faqs.length === 0 ? <section className="mt-10 rounded-lg border border-white/10 bg-white/[0.04] p-6 text-slate-300" aria-labelledby="faq-empty"><h2 id="faq-empty" className="text-xl font-semibold text-white">No questions are available yet</h2><p className="mt-2">Please contact our team with your question.</p></section> : <div className="mt-10 space-y-10">{Object.entries(groups).map(([category, items]) => <section key={category} aria-labelledby={`faq-category-${category}`}><div className="mb-4"><p className="eyebrow">{categoryLabels[category] ?? category.replace(/[-_]/g, ' ')}</p><h2 id={`faq-category-${category}`} className="mt-2 text-2xl font-semibold text-white sm:text-3xl">{categoryLabels[category] ?? category.replace(/[-_]/g, ' ')}</h2></div><div className="rounded-lg border border-white/10 bg-white/[0.04] px-5 sm:px-6">{items.map((item) => <FAQAccordion question={item.question} answer={item.answer} key={item.id} />)}</div></section>)}</div>}<section className="mt-14 rounded-lg border border-emerald-300/20 bg-[#103d4a] p-7 sm:flex sm:items-center sm:justify-between sm:gap-8 sm:p-9" aria-labelledby="faq-support-title"><div><p className="eyebrow">Client support</p><h2 id="faq-support-title" className="mt-3 text-2xl font-semibold text-white sm:text-3xl">Still have questions?</h2><p className="mt-3 max-w-2xl text-slate-200">Send the team a general enquiry, consultation request, investment-product question, or client-service request.</p></div><Link className="button button-light mt-6 shrink-0 sm:mt-0" to="/contact">Contact client services</Link></section></main></PublicShell>;
}
