import { useEffect, type FormEvent } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { investmentService, type InvestmentOpportunity } from './investmentService';

const riskLabel = (risk: string) => risk.replace('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
function PublicShell({ children }: { children: React.ReactNode }) { return <div className="min-h-screen bg-slate-50 text-slate-950"><a href="#content" className="sr-only focus:not-sr-only">Skip to content</a><header className="border-b bg-[#07192f] text-white"><nav aria-label="Primary" className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link className="text-xl font-semibold" to="/">PerrymanFinance</Link><Link to="/investments">Investment opportunities</Link></nav></header>{children}<footer className="mt-20 bg-[#07192f] px-5 py-10 text-sm text-slate-300"><div className="mx-auto max-w-6xl">Investment information is general information only and does not constitute an offer, recommendation, or guarantee. Capital is at risk.</div></footer></div>; }
function Loading() { return <p aria-busy="true" className="py-12">Loading investment information…</p>; }
function ErrorState() { return <p role="alert" className="my-8 rounded-lg border border-rose-300 bg-rose-50 p-4">Investment information is unavailable. Please try again.</p>; }
function RiskNotice({ children }: { children?: React.ReactNode }) { return <aside aria-label="Risk notice" className="rounded-xl border-l-4 border-amber-500 bg-amber-50 p-5 text-slate-800"><h2 className="font-semibold">Important risk notice</h2><div className="mt-2 text-sm">{children ?? 'Digital assets and investment strategies involve risk, including possible loss of capital. Review the opportunity-specific information and request professional advice where appropriate.'}</div></aside>; }
export function InvestmentCard({ item }: { item: InvestmentOpportunity }) { return <article className="flex flex-col rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-4 flex justify-between gap-4 text-xs font-semibold uppercase tracking-wide text-slate-500"><span>{item.category_name}</span><span>{riskLabel(item.risk_classification)} risk</span></div><h2 className="text-xl font-semibold"><Link to={`/investments/${item.slug}`}>{item.title}</Link></h2><p className="mt-3 flex-1 text-slate-600">{item.short_description}</p><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-500">Horizon</dt><dd>{item.investment_horizon ?? 'Request details'}</dd></div><div><dt className="text-slate-500">Minimum display</dt><dd>{item.minimum_investment_display ?? 'Not specified'} {item.currency_display ?? ''}</dd></div></dl><Link className="mt-6 font-semibold text-blue-800" to={`/investments/${item.slug}`}>View details →</Link></article>; }
export function InvestmentsPage() {
  const [params, setParams] = useSearchParams(); const filters = { category: params.get('category') ?? '', risk: params.get('risk') ?? '', search: params.get('search') ?? '', page: Number(params.get('page') ?? 1), per_page: 9, sort: '-published_at' };
  const investments = useQuery({ queryKey: ['investments', filters], queryFn: ({ signal }) => investmentService.publicList(filters, signal) }); const categories = useQuery({ queryKey: ['investment-categories'], queryFn: ({ signal }) => investmentService.categories(signal) });
  function filter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const next = new URLSearchParams(); for (const key of ['search', 'category', 'risk']) { const value = String(data.get(key) ?? ''); if (value) next.set(key, value); } setParams(next); }
  return <PublicShell><main id="content" className="mx-auto max-w-6xl px-5 py-14"><p className="font-semibold uppercase tracking-widest text-blue-800">Informational catalogue</p><h1 className="mt-2 text-4xl font-semibold">Investment opportunities</h1><p className="mt-4 max-w-3xl text-lg text-slate-600">Explore strategies and request further information. No investment can be made through this website.</p><form className="my-8 grid gap-4 rounded-xl bg-white p-5 shadow-sm md:grid-cols-4" onSubmit={filter}><label>Search<input name="search" defaultValue={filters.search} className="mt-1 w-full rounded border p-2" /></label><label>Category<select name="category" defaultValue={filters.category} className="mt-1 w-full rounded border p-2"><option value="">All categories</option>{categories.data?.data.map((category) => <option value={category.slug} key={category.id}>{category.name}</option>)}</select></label><label>Risk<select name="risk" defaultValue={filters.risk} className="mt-1 w-full rounded border p-2"><option value="">All risk levels</option><option value="low">Low</option><option value="moderate">Moderate</option><option value="high">High</option><option value="very_high">Very high</option></select></label><button className="self-end rounded bg-[#0b376d] px-4 py-2 font-semibold text-white">Apply filters</button></form><RiskNotice />{investments.isPending ? <Loading /> : investments.isError ? <ErrorState /> : investments.data.data.length === 0 ? <p className="py-12">No published opportunities match these filters.</p> : <div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{investments.data.data.map((item) => <InvestmentCard item={item} key={item.uuid} />)}</div>}{(investments.data?.meta.total_pages ?? 0) > 1 && <nav aria-label="Investment pagination" className="mt-8 flex gap-3"><button disabled={filters.page <= 1} onClick={() => { params.set('page', String(filters.page - 1)); setParams(params); }}>Previous</button><span>Page {filters.page} of {investments.data?.meta.total_pages}</span><button disabled={filters.page >= (investments.data?.meta.total_pages ?? 1)} onClick={() => { params.set('page', String(filters.page + 1)); setParams(params); }}>Next</button></nav>}</main></PublicShell>;
}
export function InvestmentDetailPage() {
  const { slug = '' } = useParams(); const query = useQuery({ queryKey: ['investment', slug], queryFn: ({ signal }) => investmentService.publicDetail(slug, signal), enabled: Boolean(slug) }); const item = query.data?.data;
  useEffect(() => { if (item?.seo?.meta_title) document.title = item.seo.meta_title; }, [item]);
  return <PublicShell><main id="content" className="mx-auto max-w-4xl px-5 py-14">{query.isPending ? <Loading /> : query.isError || !item ? <ErrorState /> : <><nav aria-label="Breadcrumb" className="text-sm text-slate-600"><Link to="/investments">Investments</Link> / {item.title}</nav><p className="mt-10 font-semibold uppercase tracking-wide text-blue-800">{item.category_name} · {riskLabel(item.risk_classification)} risk</p><h1 className="mt-2 text-4xl font-semibold">{item.title}</h1><p className="mt-5 text-xl text-slate-600">{item.short_description}</p><div className="my-8"><RiskNotice><span dangerouslySetInnerHTML={{ __html: item.disclaimer }} /></RiskNotice></div><section className="prose max-w-none" dangerouslySetInnerHTML={{ __html: item.full_description }} /><div className="mt-10 grid gap-6 md:grid-cols-2"><section><h2 className="text-xl font-semibold">Strategy summary</h2><div className="mt-2 text-slate-700" dangerouslySetInnerHTML={{ __html: item.strategy_summary ?? 'Further details are available on request.' }} /></section><section><h2 className="text-xl font-semibold">Investment objective</h2><div className="mt-2 text-slate-700" dangerouslySetInnerHTML={{ __html: item.investment_objective ?? 'Further details are available on request.' }} /></section></div><dl className="my-10 grid gap-4 rounded-xl bg-slate-100 p-6 sm:grid-cols-3"><div><dt className="text-sm text-slate-500">Horizon</dt><dd>{item.investment_horizon ?? 'Request details'}</dd></div><div><dt className="text-sm text-slate-500">Risk</dt><dd>{riskLabel(item.risk_classification)}</dd></div><div><dt className="text-sm text-slate-500">Minimum display</dt><dd>{item.minimum_investment_display ?? 'Not specified'} {item.currency_display ?? ''}</dd></div></dl><section className="rounded-2xl bg-[#07192f] p-8 text-white"><h2 className="text-2xl font-semibold">Request more information</h2><p className="mt-2 text-slate-300">Speak with the team about this opportunity and its risks.</p><Link to={`/contact?investment=${encodeURIComponent(item.slug)}`} className="mt-5 inline-block rounded bg-emerald-300 px-5 py-3 font-semibold text-slate-950">Request Information</Link></section></>}</main></PublicShell>;
}
