import { useState, type FormEvent } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { ApiError } from '../../services/apiClient';
import { cmsService, type CmsPage, type LegalDocument, type SeoMetadata } from './cmsService';
import { useLegal, useMedia, usePages, useSavePage, useSettings } from './useCms';

function State({ pending, error, empty }: { pending: boolean; error: boolean; empty?: boolean }) {
  if (pending) return <p aria-busy="true">Loading content…</p>;
  if (error) return <p className="text-rose-300" role="alert">Content could not be loaded.</p>;
  if (empty) return <p className="rounded-xl border border-slate-800 p-5 text-slate-400">No records yet.</p>;
  return null;
}

const inputClass = 'mt-1 w-full rounded-lg border border-slate-600 bg-slate-900 px-3 py-2 text-white';
const buttonClass = 'rounded-lg bg-emerald-300 px-4 py-2 font-semibold text-slate-950 disabled:opacity-50';

export function PagesScreen() {
  const pages = usePages(); const save = useSavePage(); const [editing, setEditing] = useState<Partial<CmsPage> | null>(null); const [message, setMessage] = useState('');
  const draft = editing ?? { title: '', slug: '', page_type: 'marketing', status: 'draft', excerpt: '', sections: [{ type: 'hero', content: { heading: '' } }] };
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(''); try { const result = await save.mutateAsync(draft); setEditing(result.data); setMessage('Page saved.'); } catch (error) { setMessage(error instanceof ApiError ? error.message : 'Page could not be saved.'); } }
  return <main><div className="flex items-center justify-between"><h1 className="text-3xl font-semibold">Pages</h1><button className={buttonClass} onClick={() => setEditing({ title: '', slug: '', page_type: 'marketing', status: 'draft', excerpt: '', sections: [{ type: 'hero', content: { heading: '' } }] })}>New page</button></div><State pending={pages.isPending} error={pages.isError} empty={pages.data?.data.length === 0} />
    {!editing && <div className="mt-6 space-y-3">{pages.data?.data.map((page) => <button className="flex w-full justify-between rounded-xl border border-slate-800 p-4 text-left" key={page.uuid} onClick={async () => setEditing((await cmsService.page(page.uuid)).data)}><span>{page.title}</span><span className="text-slate-400">{page.status}</span></button>)}</div>}
    {editing && <form className="mt-6 space-y-4" onSubmit={submit}><label className="block">Title<input className={inputClass} required value={draft.title ?? ''} onChange={(e) => setEditing({ ...draft, title: e.target.value })} /></label><div className="grid gap-4 sm:grid-cols-2"><label>Slug<input className={inputClass} required value={draft.slug ?? ''} onChange={(e) => setEditing({ ...draft, slug: e.target.value })} /></label><label>Page type<input className={inputClass} required value={draft.page_type ?? ''} onChange={(e) => setEditing({ ...draft, page_type: e.target.value })} /></label></div><label className="block">Excerpt<textarea className={inputClass} value={draft.excerpt ?? ''} onChange={(e) => setEditing({ ...draft, excerpt: e.target.value })} /></label><label className="block">Structured sections (JSON)<textarea className={`${inputClass} min-h-52 font-mono text-sm`} value={JSON.stringify(draft.sections ?? [], null, 2)} onChange={(e) => { try { setEditing({ ...draft, sections: JSON.parse(e.target.value) }); } catch { /* Retain the last valid structure. */ } }} /></label><div className="flex flex-wrap gap-3"><button className={buttonClass} disabled={save.isPending}>Save</button>{draft.status === 'draft' && <button type="button" className={buttonClass} onClick={() => setEditing({ ...draft, status: 'review' })}>Submit for review</button>}{draft.status === 'review' && <button type="button" className={buttonClass} onClick={() => setEditing({ ...draft, status: 'published' })}>Publish</button>}{draft.status === 'published' && <button type="button" className={buttonClass} onClick={() => setEditing({ ...draft, status: 'archived' })}>Archive</button>}<button type="button" className="rounded-lg border border-slate-600 px-4 py-2" onClick={() => setEditing(null)}>Back</button></div>{message && <p role="status">{message}</p>}<details className="rounded-xl border border-slate-800 p-4"><summary>Preview</summary><h2 className="mt-4 text-2xl">{draft.title}</h2><p className="text-slate-400">{draft.excerpt}</p><pre className="mt-4 overflow-auto text-xs">{JSON.stringify(draft.sections, null, 2)}</pre></details></form>}
  </main>;
}

export function LegalScreen() {
  const query = useLegal(); const client = useQueryClient(); const [document, setDocument] = useState<Partial<LegalDocument> | null>(null); const [message, setMessage] = useState('');
  const save = useMutation({ mutationFn: cmsService.saveLegal, onSuccess: () => client.invalidateQueries({ queryKey: ['admin', 'legal'] }) });
  const value = document ?? { document_type: 'privacy_policy', title: '', slug: '', version: '1.0', content: '', effective_at: '', status: 'draft' };
  async function submit(event: FormEvent) { event.preventDefault(); try { const result = await save.mutateAsync(value); setDocument(result.data); setMessage('Legal version saved. Counsel approval remains required before publication.'); } catch (error) { setMessage(error instanceof ApiError ? error.message : 'Document could not be saved.'); } }
  return <main><div className="flex justify-between"><h1 className="text-3xl font-semibold">Legal documents</h1><button className={buttonClass} onClick={() => setDocument({ document_type: 'privacy_policy', title: '', slug: '', version: '1.0', content: '', effective_at: '', status: 'draft' })}>New document</button></div><State pending={query.isPending} error={query.isError} empty={query.data?.data.length === 0} />{!document && <div className="mt-6 space-y-3">{query.data?.data.map((item) => <button className="flex w-full justify-between rounded-xl border border-slate-800 p-4" key={item.uuid} onClick={() => setDocument(item)}><span>{item.title} · v{item.version}</span><span>{item.status}</span></button>)}</div>}{document && <form className="mt-6 space-y-4" onSubmit={submit}><label className="block">Document type<input className={inputClass} value={value.document_type ?? ''} onChange={(e) => setDocument({ ...value, document_type: e.target.value })} /></label><label className="block">Title<input className={inputClass} value={value.title ?? ''} onChange={(e) => setDocument({ ...value, title: e.target.value })} /></label><div className="grid gap-4 sm:grid-cols-3"><label>Slug<input className={inputClass} value={value.slug ?? ''} onChange={(e) => setDocument({ ...value, slug: e.target.value })} /></label><label>Version<input className={inputClass} value={value.version ?? ''} onChange={(e) => setDocument({ ...value, version: e.target.value })} /></label><label>Effective date<input type="datetime-local" className={inputClass} value={value.effective_at?.slice(0, 16) ?? ''} onChange={(e) => setDocument({ ...value, effective_at: e.target.value })} /></label></div><label className="block">Reviewed HTML content<textarea className={`${inputClass} min-h-64`} value={value.content ?? ''} onChange={(e) => setDocument({ ...value, content: e.target.value })} /></label><label>Status<select className={inputClass} value={value.status} onChange={(e) => setDocument({ ...value, status: e.target.value })}><option>draft</option><option>review</option><option>published</option><option>archived</option></select></label><div className="flex gap-3"><button className={buttonClass} disabled={save.isPending}>Save version</button><button type="button" className="rounded-lg border px-4" onClick={() => setDocument(null)}>Back</button></div>{message && <p role="status">{message}</p>}</form>}</main>;
}

export function SettingsScreen() {
  const query = useSettings(); const client = useQueryClient(); const [key, setKey] = useState(''); const [value, setValue] = useState(''); const [isPublic, setPublic] = useState(false); const save = useMutation({ mutationFn: () => cmsService.saveSetting(key, value, isPublic), onSuccess: () => client.invalidateQueries({ queryKey: ['admin', 'settings'] }) });
  return <main><h1 className="text-3xl font-semibold">Site settings</h1><State pending={query.isPending} error={query.isError} empty={query.data?.data.length === 0} /><ul className="mt-5 space-y-2">{query.data?.data.map((setting) => <li className="rounded-lg border border-slate-800 p-3" key={setting.setting_key}>{setting.setting_key}: {JSON.stringify(setting.value)} {Boolean(setting.is_public) && <span className="text-emerald-300">public</span>}</li>)}</ul><form className="mt-8 space-y-4" onSubmit={(e) => { e.preventDefault(); void save.mutateAsync(); }}><label className="block">Setting key<input className={inputClass} required value={key} onChange={(e) => setKey(e.target.value)} /></label><label className="block">Value<input className={inputClass} required value={value} onChange={(e) => setValue(e.target.value)} /></label><label className="flex gap-2"><input type="checkbox" checked={isPublic} onChange={(e) => setPublic(e.target.checked)} />Expose through the public settings endpoint</label><button className={buttonClass} disabled={save.isPending}>Save setting</button></form></main>;
}

export function MediaScreen() {
  const query = useMedia(); const client = useQueryClient(); const [file, setFile] = useState<File | null>(null); const [alt, setAlt] = useState(''); const upload = useMutation({ mutationFn: () => file ? cmsService.upload(file, alt) : Promise.reject(new Error('Choose a file.')), onSuccess: () => client.invalidateQueries({ queryKey: ['admin', 'media'] }) });
  return <main><h1 className="text-3xl font-semibold">Media library</h1><form className="my-6 flex flex-wrap items-end gap-3" onSubmit={(e) => { e.preventDefault(); void upload.mutateAsync(); }}><label>Image<input className={inputClass} type="file" accept="image/jpeg,image/png,image/webp" required onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></label><label>Alt text<input className={inputClass} value={alt} onChange={(e) => setAlt(e.target.value)} /></label><button className={buttonClass} disabled={upload.isPending}>Upload</button></form>{upload.isError && <p role="alert" className="text-rose-300">Upload failed. Check the image type and size.</p>}<State pending={query.isPending} error={query.isError} empty={query.data?.data.length === 0} /><div className="grid gap-4 sm:grid-cols-2">{query.data?.data.map((asset) => <article className="rounded-xl border border-slate-800 p-4" key={asset.uuid}><h2>{asset.original_name}</h2><p className="text-sm text-slate-400">{asset.mime_type} · {asset.width}×{asset.height} · {asset.byte_size} bytes</p><p>{asset.alt_text}</p></article>)}</div></main>;
}

export function SeoScreen() {
  const pages = usePages(); const legal = useLegal(); const [type, setType] = useState<'page' | 'legal_document'>('page'); const [uuid, setUuid] = useState(''); const [form, setForm] = useState<SeoMetadata>({ meta_title: '', meta_description: '', canonical_url: '', robots: 'index,follow', open_graph: {} }); const save = useMutation({ mutationFn: () => cmsService.saveSeo(type, uuid, form) }); const owners = type === 'page' ? pages.data?.data : legal.data?.data;
  return <main><h1 className="text-3xl font-semibold">SEO editor</h1><State pending={pages.isPending || legal.isPending} error={pages.isError || legal.isError} /><form className="mt-6 space-y-4" onSubmit={(e) => { e.preventDefault(); void save.mutateAsync(); }}><label className="block">Content type<select className={inputClass} value={type} onChange={(e) => { setType(e.target.value as 'page' | 'legal_document'); setUuid(''); }}><option value="page">Page</option><option value="legal_document">Legal document</option></select></label><label className="block">Content item<select className={inputClass} required value={uuid} onChange={(e) => setUuid(e.target.value)}><option value="">Select content</option>{owners?.map((owner) => <option key={owner.uuid} value={owner.uuid}>{owner.title}</option>)}</select></label><label className="block">Meta title<input className={inputClass} required value={form.meta_title} onChange={(e) => setForm({ ...form, meta_title: e.target.value })} /></label><label className="block">Meta description<textarea className={inputClass} required value={form.meta_description} onChange={(e) => setForm({ ...form, meta_description: e.target.value })} /></label><label className="block">Canonical URL<input type="url" className={inputClass} value={form.canonical_url ?? ''} onChange={(e) => setForm({ ...form, canonical_url: e.target.value })} /></label><label>Robots<select className={inputClass} value={form.robots} onChange={(e) => setForm({ ...form, robots: e.target.value })}><option>index,follow</option><option>noindex,follow</option><option>noindex,nofollow</option></select></label><button className={buttonClass} disabled={save.isPending}>Save SEO metadata</button>{save.isSuccess && <p role="status">SEO metadata saved.</p>}</form></main>;
}
